services:
  app:
    build:
      context: ..
      dockerfile: docker/dev.Dockerfile
    env_file: .env  # Used for testing with prod secrets, NEVER committed.
    environment:
      DEV:       1
      GOCACHE:   /tmp
      GOPATH:    /tmp
      PGHOST:    db
      PGSSLMODE: disable
      PGUSER:    code-golf
    pids_limit: 1024
    privileged: true
    user: 1000:1000
    volumes:
      - ..:/go
  db:
    image: postgres:14.5-alpine
    environment:
      POSTGRES_DB: code-golf
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ../db:/docker-entrypoint-initdb.d
